parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: environment
  displayName: Environment
  type: string
  default: Sandbox
  values:
  - Preview
  - Dev
  - AAT
  - Sandbox
  - Test1
  - Test2
  - Test3
  - Demo
  - Preprod
  - Prod

- name: RunZap
  displayName: Execute ZAP Tests
  type: boolean
  default: false

- name: prodEnvs
  displayName: Environments Using Prod Subscription
  type: object
  default:
    - Prod
    - Preprod

# Set variables once
variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-booking-queue-subscriber
  - group: vh-video-web-nonprod
  - ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    - ${{ if containsValue(parameters.prodEnvs, parameters.environment) }}:
      - group: vh-prod
      - group: vh-video-web-prod
    - ${{ if not(containsValue(parameters.prodEnvs, parameters.environment)) }}:
      - group: vh-preview
  - ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    - ${{ if or(startswith(variables['Build.SourceBranch'], 'refs/heads/release/'), startswith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - group: vh-prod
      - group: vh-video-web-prod
    - ${{ if not(or(startswith(variables['Build.SourceBranch'], 'refs/heads/release/'), startswith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))) }}:
      - group: vh-preview
    - ${{ if containsValue("Preprod", parameters.environment) }}:  
      - group: vh-video-web-preprod


trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts
  pipelines:
  - pipeline: CI
    source: hmcts.vh-booking-queue-subscriber
    trigger: 
      branches:
      - master
      - hotfix/*
      - release/*


stages:
  - template: templates/vh-release.yml@templates
    parameters:
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        environments:
          - ${{ parameters.environment }}
        deploymentBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deploymentBranch: resources.pipeline.CI.sourceBranch
      releaseParameters:
        runZapTests: ${{ parameters.RunZap }}
        subscription: $(env_Subscription)
        secrets_KeyVault: $(env_Secret_KeyVault)
        secrets_Subscription: $(env_Secret_Subscription)
        devOpsResource: vh_booking_queue_subscriber
        deploymentSlot: production
        appName: vh-booking-queue-subscriber-$(environment)
        resourceGroup: vh-booking-queue-subscriber-$(environment)
        testCaseFilter:
        dependentApps:
        - name: vh-bookings-api-$(environment)
          resourceGroup: vh-bookings-api-$(environment)
          healthEndpoint: $(bookings_api_url)healthcheck/health
        - name: vh-video-api-$(environment)
          resourceGroup: vh-video-api-$(environment)
          healthEndpoint: $(video_api_url)healthcheck/health
        variables:
          - name: AppUri
            value: $(AppUri_Prod)
            env:
             - Prod
          - group: vh-video-web-nonprod
            env:
             - Preview
             - Dev
             - AAT
             - Sandbox
             - Test1
             - Test2
          - group: vh-video-web-preprod
            env:
             - Preprod
          - group: vh-video-web-prod
            env:
             - Prod  

        appSettings:
          - name: ApplicationInsights:InstrumentationKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: AppInsightsKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: AzureAd:ClientId
            value: vh-booking-queue-subscriber-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-booking-queue-subscriber-key
            secret: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: VhServices:BookingsApiResourceId
            value: vh-bookings-api-identifieruris
            secret: true
          - name: VhServices:BookingsApiUrl
            value: $(bookings_api_url)
          - name: VhServices:VideoApiResourceId   
            value: vh-video-api-identifieruris
            secret: true
          - name: VhServices:VideoApiUrl
            value: $(video_api_url)
          - name: VhServices:VideoWebResourceId   
            value: vh-video-web-identifieruris
            secret: true
          - name: VhServices:VideoWebUrl
            value: $(video_web_url)
          - name: VhServices:InternalEventSecret
            value: $(internal_event_secret)
        acceptanceTestSettings:
          - name: AzureAd:ClientId
            value: vh-booking-queue-subscriber-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-booking-queue-subscriber-key
            secret: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: VhServices:BookingsApiResourceId
            value: vh-bookings-api-identifieruris
            secret: true
          - name: VhServices:BookingsApiUrl
            value: $(bookings_api_url)
          - name: VhServices:VideoApiResourceId   
            value: vh-video-api-identifieruris
            secret: true
          - name: VhServices:VideoApiUrl
            value: $(video_api_url)
          - name: VhServices:VideoWebResourceId   
            value: vh-video-web-identifieruris
            secret: true
          - name: VhServices:VideoWebUrl
            value: $(video_web_url)
          - name: VhServices:InternalEventSecret
            value: $(internal_event_secret)
          - name: UsernameStem
            value: $(UsernameStem)