parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: environment
  displayName: Environment
  type: string
  default: AAT
  values:
  - Preview
  - Dev
  - AAT
  - Sandbox
  - Test1
  - Test2
  - Test3
  - Demo
  - Preprod
  - Prod

- name: deviceConfiguration
  displayName: Device Configurations
  type: object
  default:
    - OS: Windows
      Browser: Chrome
      BrowserVersion: Latest
      DeviceType: Desktop
      DeviceName:
      TestCaseFilter: 

- name: prodEnvs
  displayName: Environments Using Prod Subscription
  type: object
  default:
    - Prod
    - Preprod

# Set variables once
variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-booking-queue-subscriber
  - group: vh-preview
  - ${{ if containsValue(parameters.prodEnvs, parameters.environment) }}:
    - group: vh-prod
  - ${{ if not(containsValue(parameters.prodEnvs, parameters.environment)) }}:
    - group: vh-preview
  - group: vh-video-web-nonprod

trigger: none
pr: none
schedules:
- cron: "0 20 * * *"
  displayName: Daily midnight build
  always: true
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts
  pipelines:
  - pipeline: CI
    source: hmcts.vh-booking-queue-subscriber

stages:
  - template: templates/vh-release.yml@templates
    parameters:
      environments:
        - ${{ parameters.environment }}
      deploymentBranch: ${{ parameters.deploymentBranch }}
      releaseParameters:
        subscription: $(env_Subscription)
        secrets_KeyVault: $(env_Secret_KeyVault)
        secrets_Subscription: $(env_Secret_Subscription)
        devOpsResource: vh_booking_queue_subscriber
        appName: vh-booking-queue-subscriber-$(environment)
        resourceGroup: vh-booking-queue-subscriber-$(environment)
        testCaseFilter:
        dependentApps:
        - name: vh-bookings-api-$(environment)
          resourceGroup: vh-bookings-api-$(environment)
          healthEndpoint: $(bookings_api_url)healthcheck/health
        - name: vh-video-api-$(environment)
          resourceGroup: vh-video-api-$(environment)
          healthEndpoint: $(video_api_url)healthcheck/health
        appSettings:
        - name: ApplicationInsights:InstrumentationKey
          value: vh-core-infra-AppInsightsKey
          secret: true
        - name: AppInsightsKey
          value: vh-core-infra-AppInsightsKey
          secret: true
        
        # AzureAd
        - name: AzureAd:ClientId
          value: vh-booking-queue-subscriber-appid
          secret: true
        - name: AzureAd:ClientSecret
          value: vh-booking-queue-subscriber-key
          secret: true
        - name: AzureAd:TenantId
          value: tenantid
          secret: true

        # VhServices
        - name: VhServices:BookingsApiResourceId
          value: vh-bookings-api-identifieruris
          secret: true
        - name: VhServices:BookingsApiUrl
          value: $(bookings_api_url)
        - name: VhServices:VideoApiResourceId   
          value: vh-video-api-identifieruris
          secret: true
        - name: VhServices:VideoApiUrl
          value: $(video_api_url)
        - name: VhServices:VideoWebResourceId   
          value: vh-video-web-identifieruris
          secret: true
        - name: VhServices:VideoWebUrl
          value: $(video_web_url)
        - name: VhServices:InternalEventSecret
          value: $(internal_event_secret)

        acceptanceTestSettings:
          - name: AzureAd:ClientId
            value: vh-booking-queue-subscriber-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-booking-queue-subscriber-key
            secret: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: VhServices:BookingsApiResourceId
            value: vh-bookings-api-identifieruris
            secret: true
          - name: VhServices:BookingsApiUrl
            value: $(bookings_api_url)
          - name: VhServices:VideoApiResourceId   
            value: vh-video-api-identifieruris
            secret: true
          - name: VhServices:VideoApiUrl
            value: $(video_api_url)
          - name: VhServices:VideoWebResourceId   
            value: vh-video-web-identifieruris
            secret: true
          - name: VhServices:VideoWebUrl
            value: $(video_web_url)
          - name: VhServices:InternalEventSecret
            value: $(internal_event_secret)
          - name: UsernameStem
            value: $(UsernameStem)
        runMultiDeviceTests: false
        deviceConfiguration: ${{ parameters.deviceConfiguration }}
