# Set variables once
variables:
  solutionType: DotNetCore # angularDotNetCore, dotNetCore, angular
  apiDirectory: 'BookingQueueSubscriber/BookingQueueSubscriber'
  sonarCloudExtraProperties: |
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
    sonar.coverage.exclusions=**/VideoApiService.cs, **/Startup.cs, **/Testing.Common/**, **/BookingQueueSubscriber.Common/ApiHelper/**, **/BookingQueueSubscriber.Common/Helper/Configuration/**, **/BookingQueueSubscriber.Common/Helper/Security/**
  coverletCoverageExclusions: '[*]BookingQueueSubscriber.Common.*,[BookingQueueSubscriber.Services]BookingQueueSubscriber.Services.VideoApiService,[*]BookingQueueSubscriber.UnitTests.*,[BookingQueueSubscriber]BookingQueueSubscriber.Startup'
  integrationTestsAppSettingsTransform: '
    "AzureAd/TenantId":"$(tenantid)",
    "AzureAd/ClientId":"$(vh-booking-queue-subscriber-appid)",
    "AzureAd/ClientSecret":"$(vh-booking-queue-subscriber-key)",
    "AzureAd/VideoApiResourceId":"$(vh-video-api-identifieruris)",
    "VhServices/VideoApiUrl":"$(VideoApiUri)",
    "VhServices/EnableVideoApiStub":"true"
    '
  dalWorkingDirectory: ''
  keyVaultName: vhcoreinfrahtdev # Used to get secrets for integration tests
  secretsFilter: 'tenantid,vh-bookings-api-identifieruris' # filters out secrets returned from key vault
  infraKeyVaultName: 'vhcoreinfradev'
  infraSecretsFilter: 'vh-core-infra-AppInsightsKey'


# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    ref: refs/heads/master # ref name to use, defaults to 'refs/heads/master'
    endpoint: 'GitHubDevOps'

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*
pr:
  - master

jobs:
  
- template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
  parameters:
    sonarCloudExtraProperties: $(sonarCloudExtraProperties)
    integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
    coverletCoverageExclusions: $(coverletCoverageExclusions)
    apiDirectory: $(apiDirectory)
    dalWorkingDirectory: $(dalWorkingDirectory)
    keyVaultName: $(keyVaultName)
    secretsFilter: $(secretsFilter)
    infraKeyVaultName: $(infraKeyVaultName)
    infraSecretsFilter: $(infraSecretsFilter)

