version: '3.4'

services:
  bookingqueuesubscriber:
    image: ${DOCKER_REGISTRY-}bookingqueuesubscriber:latest
    build:
      context: .
      dockerfile: BookingQueueSubscriber/BookingQueueSubscriber/Dockerfile
