version: '3.4'

services:
  bookingqueuesubscriber:
    image: ${DOCKER_REGISTRY-}bookingqueuesubscriber:local
    build:
      context: .
      dockerfile: BookingQueueSubscriber/BookingQueueSubscriber/Dockerfile
    volumes:
      - ~/.microsoft/usersecrets/:/root/.microsoft/usersecrets:ro
      - ~/mnt/secrets:/mnt/secrets:ro
