---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    QUEUENAME: shaed-dev
    VHSERVICES__BOOKINGSAPIURL : https://vh-bookings-api-pr-945.dev.platform.hmcts.net/
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: shaed-dev
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'