---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    QUEUENAME: booking-will
    VHSERVICES__BOOKINGSAPIURL: https://vh-booking-api-pr-857.dev.platform.hmcts.net/
    VHSERVICES__ENABLEVIDEOAPISTUB: false
    VHSERVICES__VIDEOAPIURL:  https://vh-admin-web-pr-646.dev.platform.hmcts.net/
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: booking
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'