---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    VHSERVICES__VIDEOWEBURL: https://vh-video-web-pr-2026.dev.platform.hmcts.net/
    VHSERVICES__VIDEOAPIURL: https://vh-video-api-pr-584.dev.platform.hmcts.net/
    QUEUENAME: booking-will
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
    - type: azure-servicebus
      serviceBusName: "vh-infra-core-dev"
      queueName: booking
      messageCount: 1
  object:
    name: '${RELEASE_NAME}'
