---
function:
  image: '${IMAGE_NAME}'
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-demo"
    queueName: booking
    messageCount: 1
    failureThreshold: 3
    replicas: 2
  object:
    apiVersion: apps/v1
    kind: Deployment
    name: '${RELEASE_NAME}'
    pollingInterval: 30
    cooldownPeriod: 90
    idleReplicaCount: 0
    maxReplicaCount: 1