---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    QUEUENAME: marco-dev-booking
    VHSERVICES__NOTIFICATIONAPIURL: https://vh-notification-api-pr-151.dev.platform.hmcts.net/
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: booking
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'