---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  disableTraefikTls: false
  environment:
    QUEUENAME: booking-will
    VHSERVICES__VIDEOAPIURL: https://vh-video-api-pr-735.dev.platform.hmcts.net/