---
java:
  image: "${IMAGE_NAME}"
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    VHSERVICES__BOOKINGSAPIURL: https://vh-bookings-api-pr-691.dev.platform.hmcts.net/
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
    - type: azure-servicebus
      serviceBusName: "vh-infra-core-dev"
      queueName: booking
      messageCount: 1
  object:
    name: "${RELEASE_NAME}"
