---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    QUEUENAME: marco-dev-booking-notexist
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    #queueName: marco-dev-booking
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'
