---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    QUEUENAME: booking-will-with-retries
    VHSERVICES__BOOKINGSAPIURL: https://vh-booking-api-pr-816.dev.platform.hmcts.net/
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: booking-will-with-retries
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'