---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    QUEUENAME: oliver-booking
    VHSERVICES__VIDEOWEBURL : https://vh-video-web-pr-2165.dev.platform.hmcts.net/
    VHSERVICES__VIDEOAPIURL: https://vh-video-api-pr-656.dev.platform.hmcts.net/
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: oliver-booking
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'