---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    QUEUENAME: oliver-booking
    VHSERVICES__BOOKINGSAPIURL: https://vh-bookings-api-pr-950.dev.platform.hmcts.net/
    VHSERVICES__USERAPIURL: https://vh-user-api-pr-264.dev.platform.hmcts.net/
    VHSERVICES__NOTIFICATIONAPIURL: https://vh-notification-api-pr-178.dev.platform.hmcts.net/
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: oliver-booking
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'