---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  disableTraefikTls: false
  environment:
    QUEUENAME: booking-will
    VHSERVICES__USERAPIURL: https://vh-user-api-pr-279.dev.platform.hmcts.net/