---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: booking
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'
environment: # TODO for testing only, do not merge
  VHSERVICES__VIDEOWEBURL : https://vh-video-web-pr-1999.dev.platform.hmcts.net/
  QUEUENAME : marco-dev-booking