---
java:
  image: '${IMAGE_NAME}'
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    VHSERVICES__VIDEOAPIURL: https://vh-video-api-pr-579.dev.platform.hmcts.net/
    VHSERVICES__BOOKINGSAPIURL: https://vh-bookings-api-pr-642.dev.platform.hmcts.net/
    QUEUENAME: booking-will-with-retries
function:
  releaseNameOverride: ${RELEASE_NAME}
  triggers:
  - type: azure-servicebus 
    serviceBusName: "vh-infra-core-dev"
    queueName: booking-will-with-retries
    messageCount: 1
  object:
    name: '${RELEASE_NAME}'
